services:
  db:
    image: postgres:16-alpine
    container_name: foodgram-db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U foodgram -d foodgram"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: matvey53/foodgram_backend:latest
    container_name: foodgram-backend
    restart: always
    env_file:
      - ../.env
    environment:
      DB_HOST: db
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: matvey53/foodgram_frontend:latest
    container_name: foodgram-front
    volumes:
      - frontend_build:/app/result_build/

  nginx:
    image: matvey53/foodgram_nginx:latest
    container_name: foodgram-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - frontend_build:/usr/share/nginx/html/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      backend:
        condition: service_started
      frontend:
        condition: service_completed_successfully

volumes:
  postgres_data:
  static_value:
  media_value:
  frontend_build:
