from pathlib import Path

TAG_NAME_MAX_LENGTH = 32
TAG_SLUG_MAX_LENGTH = 32
INGREDIENT_NAME_MAX_LENGTH = 128
INGREDIENT_UNIT_MAX_LENGTH = 64
RECIPE_NAME_MAX_LENGTH = 256
USER_EMAIL_MAX_LENGTH = 254
USER_FIRST_NAME_MAX_LENGTH = 150
USER_LAST_NAME_MAX_LENGTH = 150

MIN_COOKING_TIME = 1
MIN_INGREDIENT_AMOUNT = 1

INGREDIENTS_CSV_RELATIVE_PATH = Path('data') / 'ingredients.csv'
